"""Protocol интерфейс для клиента эмбеддингов."""

from typing import TYPE_CHECKING, Optional, Protocol, runtime_checkable

if TYPE_CHECKING:
    from src.config import Settings
    from src.embeddings.providers.base import BaseEmbeddingProvider


@runtime_checkable
class IEmbeddingsClient(Protocol):
    """Интерфейс клиента эмбеддингов."""

    async def initialize_provider(self) -> None: ...
    async def get_embedding(self, text: str) -> list[float]: ...
    async def get_embeddings_batch(
        self, texts: list[str], batch_size: int = 10
    ) -> list[list[float]]: ...
    async def check_health(self) -> bool: ...
    async def get_models(self) -> list[str]: ...
    def get_model_name(self) -> str: ...
    async def close(self) -> None: ...
    async def reload_provider(self, config: Optional["Settings"] = None) -> None: ...

    @property
    def provider(self) -> "BaseEmbeddingProvider": ...

    @property
    def embedding_dim(self) -> int: ...
