"""Protocol интерфейс для сервиса переиндексации."""

from typing import TYPE_CHECKING, Any, Optional, Protocol

if TYPE_CHECKING:
    from src.reindex.models import ReindexPriority


class IReindexService(Protocol):
    """Интерфейс сервиса переиндексации."""

    def schedule_reindex(
        self,
        priority: "ReindexPriority" = ...,
        batch_size: Optional[int] = None,
        delay: Optional[float] = None,
        force: bool = False,
    ) -> str: ...
    async def pause(self) -> None: ...
    async def resume(self) -> None: ...
    async def cancel_current_task(self) -> bool: ...
    def clear_queue(self) -> int: ...
    def get_status(self) -> dict[str, Any]: ...
    def get_progress(self) -> dict[str, Any]: ...
    async def get_task_history(self, limit: int = 10) -> list[dict[str, Any]]: ...
    async def start_background_service(self) -> None: ...
    async def stop_background_service(self) -> None: ...
